[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-web"
version = "0.0.1"
dependencies = []

[tool.setuptools]
packages = ["simple_web"]
