[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "json-server"
version = "0.0.1"
dependencies = []

[tool.setuptools]
packages = ["json_server"]
